##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## Build my_hunter
##

CC = gcc
CFLAGS = -Wall -Wextra -Werror -I. -I./src/ -L . -lmy -MMD -MP
LDFLAGS = -L . -lmy
RM = rm -f

MAIN_SRC = ./src/main.c
SRC = ./src/Window/window.c
SRC_TEST = ./tests/test.c
OBJS = $(MAIN_SRC:.c=.o) $(SRC:.c=.o)
TEST_OBJS = $(SRC:.c=.o) $(SRC_TEST:.c=.o)

LIB_PATH = ./lib/my

NAME_TEST = unit_tests
NAME := my_hunter

VALGRINDFLAGS = -s --leak-check=full --error-exitcode=1
VALGRINDEXECFLAGS =

.PHONY: all build_lib clean_lib fclean_lib clean fclean re tests_run \
	valgrind tests_clean

all: $(NAME)

$(NAME): build_lib $(OBJS)
	$(CC) $(OBJS) -o $(NAME) $(LDFLAGS)

$(NAME_TEST): build_lib $(TEST_OBJS)
	$(CC) $(TEST_OBJS) -o $(NAME_TEST) $(LDFLAGS) --coverage -lcriterion

# Rule for building object files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

build_lib:
	make -C $(LIB_PATH)

clean_lib:
	make clean -C $(LIB_PATH)

fclean_lib:
	make fclean -C $(LIB_PATH)

clean: clean_lib
	$(RM) $(NAME) $(NAME_TEST) *.gcno *.gcda *.o *.d

fclean: clean fclean_lib

re: fclean all

tests_run: $(NAME_TEST)
	./$(NAME_TEST)

valgrind: $(NAME)
	valgrind $(VALGRINDFLAGS) ./$(NAME) $(VALGRINDEXECFLAGS)

# Include the dependency files generated by GCC
-include $(OBJS:.o=.d) $(TEST_OBJS:.o=.d)
